### ISSUE TITLE
5/21 users앱 관련 확인해야할 사항

### ISSUE THREAD

**Issue by leeceo97** [prography-8th-6team/server#6]
1. middleware 주석 처리: 따로 건든건 없고 주석처리만 진행했어 -> 왜 제대로 동작을 안하는지는 한번 알아봐줘

2. 일단 준영이 토큰이 잘못된건 아니고 설정상 nickname을 못받아온거라서 일단 닉네임 없어도 문제없게 변경해뒀어 이건 nickname이 중복됐을때 어떻게 처리할지랑도 관련있어서 참고해서 수정해주면될것 같아 --> DB에서 닉네임 조회한뒤에 이미 존재하고 있는 닉네임이면 어떻게 처리할지 고려해보면 될것 같아

3. status_code 회원가입시엔 201, 로그인시엔 200반환하게 message변경해뒀어 --> response값들 몇가지 명시해둔걸로 보이는데 이게 과연 더 명확하게 전달되고 있는지에 관해서는 우리가 논의해봐야할것 같아

4.python 컨벤션 지켜서 코드 짜는게 좋을것 같은데 kakaoURL -> kakao_url이런식으로 스네이크 케이스로 코드는 변경하는게 좋을것 같아! + 클래스명은 카멜케이스가 맞는데 함수명 같은경우 스네이크 케이스로 알고 있어서 이것도 확인후에 변경 고려해줘

5. 지금 users modelviewset사용이 맞는지?는 확인이 필요해보여 user관련한 뷰가 현재 필요한게 카카오 소셜로그인용밖에없는데 굳이 crud 뷰 전체를 열어두는게 좋다고 생각은안들어서 이것도 변경했으면 좋겠어!

6. swagger커스텀좀 더 자세하게 해둬야할것 같아. 굳이 serializer로 하는것 말고도 방법이 있어서 클라이언트가 더 명확하게 보기 위해서 잘 만들어야할듯!

7. travel쪽은 일단 테스트 용도로 만들어만 둔것 같은데 클라쪽에서 필요한 response가 뭔지는 화면보면서 더구체화 해야할듯해!

**Comment by o-ddong** [comment]
1. middleware 부분 문제는 파악했고, 수정해서 올려둘게 ㅎㅎ
2. 이거는 우리가 닉네임 필수로 설정하면 해결될 문제니깐 Pass~
3. 웅 이거는 형주니 너 말대로 확실하게 전달해 주는게 좋을거 같아
4. 웅 이거는 몰랐는데 파이썬 컨벤션 따라서 코드 짜는걸로 하자 ㅎㅎ
5. 맞아 우리 얘기 나눈 거처럼 kakao만 빼고 user modelviewset 사용으로 가자
6. 오킹~
7. 웅 마자 이거는 구체화 필요해
